server:
  port: 3344
spring:
  application:
    name: springcloud-config3344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/daiandcheng/microservicecloud-config.git
          skip-ssl-validation: true
          username: daiandcheng
          password: dai840326555