server:
  port: 80
spring:
  application:
    name: spring-consumer-dept-openfeign
eureka: #Eureka的相关的配置信息
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
feign:
  circuitbreaker:
    enabled: true # 开启feign的熔断措施
